#ifndef __CONFIG_H
#define __CONFIG_H


/*------------------------电流发送允许---------------------*/
/**
 * @brief 用于快速注释电流发送
 * @note  
 * @param 
 */

#define GIMBAL_YAW_SENT
 #define GIMBAL_PITCH_SENT    
#define SHOOT_SEND
/*--------------------------云台参数----------------------------*/

//角度
#define NORMAL_BIG_PITCH_ANGLE 1.32f//正常模式下大pitch的目标角度
#define FOLD_BIG_PITCH_ANGLE 2.02f//折叠模式下大pitch的目标角度
#define FOLD_SMALL_YAW_ANGLE 1.48f//折叠模式下小yaw的目标角度
#define FOLD_SMALL_PITCH_ANGLE -140//折叠模式下小pitch的目标角度
#define NORMAL_SMALL_PITCH_ANGLE -170//刚进入折叠模式下小pitch的目标角度

#define YAW_LIMIT_ANGLE 0.785f //大小yaw限位
#define BIG_YAW_VISION_CONTROL_ANGLE 0.53f //大yaw视觉控制角度阈值


//系统识别
#define PID_YAW_ANGLE_RECO_MODE 0
#define PID_YAW_ANGLE_RECO_KP 0.7f//0.4
#define PID_YAW_ANGLE_RECO_KI 0
#define PID_YAW_ANGLE_RECO_KD 0
#define PID_YAW_ANGLE_RECO_IMAX_OUT 0
#define PID_YAW_ANGLE_RECO_MAX_OUT 5//5

#define PID_YAW_SPEED_RECO_MODE 0
#define PID_YAW_SPEED_RECO_KP 30.0f//20
#define PID_YAW_SPEED_RECO_KI 0.0f
#define PID_YAW_SPEED_RECO_KD 0
#define PID_YAW_SPEED_RECO_IMAX_OUT 10
#define PID_YAW_SPEED_RECO_MAX_OUT 50

#define PID_PITCH_ANGLE_RECO_MODE 0
#define PID_PITCH_ANGLE_RECO_KP 0.4f//0.4
#define PID_PITCH_ANGLE_RECO_KI 0
#define PID_PITCH_ANGLE_RECO_KD 0  
#define PID_PITCH_ANGLE_RECO_IMAX_OUT 0
#define PID_PITCH_ANGLE_RECO_MAX_OUT 5//5

#define PID_PITCH_SPEED_RECO_MODE 0
#define PID_PITCH_SPEED_RECO_KP 20.0f//20
#define PID_PITCH_SPEED_RECO_KI 0
#define PID_PITCH_SPEED_RECO_KD 0
#define PID_PITCH_SPEED_RECO_IMAX_OUT 0
#define PID_PITCH_SPEED_RECO_MAX_OUT 50
//无视觉(正常模式)
#define PID_YAW_ANGLE_MODE 0
#define PID_YAW_ANGLE_KP 0.7f
#define PID_YAW_ANGLE_KI 0
#define PID_YAW_ANGLE_KD 0
#define PID_YAW_ANGLE_IMAX_OUT 0
#define PID_YAW_ANGLE_MAX_OUT 7

#define PID_YAW_SPEED_MODE 0
#define PID_YAW_SPEED_KP 0.7f//0.8
#define PID_YAW_SPEED_KI 0
#define PID_YAW_SPEED_KD 0
#define PID_YAW_SPEED_IMAX_OUT 0
#define PID_YAW_SPEED_MAX_OUT 3

#define PID_PITCH_ANGLE_MODE 0
#define PID_PITCH_ANGLE_KP 0.6f
#define PID_PITCH_ANGLE_KI 0
#define PID_PITCH_ANGLE_KD 0
#define PID_PITCH_ANGLE_IMAX_OUT 0
#define PID_PITCH_ANGLE_MAX_OUT 7.0f

#define PID_PITCH_SPEED_MODE 0
#define PID_PITCH_SPEED_KP 0.9f
#define PID_PITCH_SPEED_KI 0
#define PID_PITCH_SPEED_KD 0
#define PID_PITCH_SPEED_IMAX_OUT 0
#define PID_PITCH_SPEED_MAX_OUT 5.0f



#define PID_MOTOR_ANGLE_MODE 0
#define PID_MOTOR_ANGLE_KP 18
#define PID_MOTOR_ANGLE_KI 0.01
#define PID_MOTOR_ANGLE_KD 0
#define PID_MOTOR_ANGLE_IOUT_MAX 1
#define PID_MOTOR_ANGLE_OUT_MAX 7

#define PID_MOTOR_SPEED_MODE 0
#define PID_MOTOR_SPEED_KP 0.17f
#define PID_MOTOR_SPEED_KI 0
#define PID_MOTOR_SPEED_KD 0
#define PID_MOTOR_SPEED_IOUT_MAX 0
#define PID_MOTOR_SPEED_OUT_MAX 5

#define PID_PITCH_MOTOR_ANGLE_MODE 0
#define PID_PITCH_MOTOR_ANGLE_KP 0.5
#define PID_PITCH_MOTOR_ANGLE_KI 0.0f
#define PID_PITCH_MOTOR_ANGLE_KD 0
#define PID_PITCH_MOTOR_ANGLE_IOUT_MAX 0
#define PID_PITCH_MOTOR_ANGLE_OUT_MAX 4

#define PID_PITCH_MOTOR_SPEED_MODE 0
#define PID_PITCH_MOTOR_SPEED_KP 0.3f
#define PID_PITCH_MOTOR_SPEED_KI 0
#define PID_PITCH_MOTOR_SPEED_KD 0
#define PID_PITCH_MOTOR_SPEED_IOUT_MAX 0
#define PID_PITCH_MOTOR_SPEED_OUT_MAX 3
//调头
#define PID_YAW_ANGLE_MODE_DT 0
#define PID_YAW_ANGLE_KP_DT 0.7f
#define PID_YAW_ANGLE_KI_DT 0
#define PID_YAW_ANGLE_KD_DT 0
#define PID_YAW_ANGLE_IMAX_OUT_DT 0
#define PID_YAW_ANGLE_MAX_OUT_DT 7

#define PID_YAW_SPEED_MODE_DT 0
#define PID_YAW_SPEED_KP_DT 0.7f//0.8
#define PID_YAW_SPEED_KI_DT 0
#define PID_YAW_SPEED_KD_DT 0
#define PID_YAW_SPEED_IMAX_OUT_DT 0
#define PID_YAW_SPEED_MAX_OUT_DT 0.7f

#define PID_PITCH_ANGLE_MODE_DT 0
#define PID_PITCH_ANGLE_KP_DT 0.6f
#define PID_PITCH_ANGLE_KI_DT 0
#define PID_PITCH_ANGLE_KD_DT 0
#define PID_PITCH_ANGLE_IMAX_OUT_DT 0
#define PID_PITCH_ANGLE_MAX_OUT_DT 7.0f

#define PID_PITCH_SPEED_MODE_DT 0
#define PID_PITCH_SPEED_KP_DT 0.9f
#define PID_PITCH_SPEED_KI_DT 0
#define PID_PITCH_SPEED_KD_DT 0
#define PID_PITCH_SPEED_IMAX_OUT_DT 0
#define PID_PITCH_SPEED_MAX_OUT_DT 5.0f



//装甲板
#define PID_YAW_VISION_ARMOR_ANGLE_MODE 0
#define PID_YAW_VISION_ARMOR_ANGLE_KP 0.65f//0.5
#define PID_YAW_VISION_ARMOR_ANGLE_KI 0.001f
#define PID_YAW_VISION_ARMOR_ANGLE_KD 0
#define PID_YAW_VISION_ARMOR_ANGLE_IMAX_OUT 0.01f
#define PID_YAW_VISION_ARMOR_ANGLE_MAX_OUT 5.0f

#define PID_YAW_VISION_ARMOR_SPEED_MODE 0
#define PID_YAW_VISION_ARMOR_SPEED_KP 0.7f
#define PID_YAW_VISION_ARMOR_SPEED_KI 0.001f
#define PID_YAW_VISION_ARMOR_SPEED_KD 0
#define PID_YAW_VISION_ARMOR_SPEED_IMAX_OUT 0.0f
#define PID_YAW_VISION_ARMOR_SPEED_MAX_OUT 4.0f

#define PID_PITCH_VISION_ARMOR_ANGLE_MODE 0
#define PID_PITCH_VISION_ARMOR_ANGLE_KP 0.45f
#define PID_PITCH_VISION_ARMOR_ANGLE_KI 0.001f
#define PID_PITCH_VISION_ARMOR_ANGLE_KD 0
#define PID_PITCH_VISION_ARMOR_ANGLE_IMAX_OUT 1.0f//1
#define PID_PITCH_VISION_ARMOR_ANGLE_MAX_OUT 5

#define PID_PITCH_VISION_ARMOR_SPEED_MODE 0
#define PID_PITCH_VISION_ARMOR_SPEED_KP 1.2f
#define PID_PITCH_VISION_ARMOR_SPEED_KI 0
#define PID_PITCH_VISION_ARMOR_SPEED_KD 0
#define PID_PITCH_VISION_ARMOR_SPEED_IMAX_OUT 0
#define PID_PITCH_VISION_ARMOR_SPEED_MAX_OUT 4


//BUFF
#define PID_YAW_VISION_BUFF_ANGLE_MODE 0
#define PID_YAW_VISION_BUFF_ANGLE_KP 0.5
#define PID_YAW_VISION_BUFF_ANGLE_KI 0
#define PID_YAW_VISION_BUFF_ANGLE_KD 0
#define PID_YAW_VISION_BUFF_ANGLE_IMAX_OUT 0
#define PID_YAW_VISION_BUFF_ANGLE_MAX_OUT 10

#define PID_YAW_VISION_BUFF_SPEED_MODE 0
#define PID_YAW_VISION_BUFF_SPEED_KP 1
#define PID_YAW_VISION_BUFF_SPEED_KI 0.01
#define PID_YAW_VISION_BUFF_SPEED_KD 0
#define PID_YAW_VISION_BUFF_SPEED_IMAX_OUT 0.5
#define PID_YAW_VISION_BUFF_SPEED_MAX_OUT 7

#define PID_PITCH_VISION_BUFF_ANGLE_MODE 0
#define PID_PITCH_VISION_BUFF_ANGLE_KP 0.8
#define PID_PITCH_VISION_BUFF_ANGLE_KI 0.003
#define PID_PITCH_VISION_BUFF_ANGLE_KD 0
#define PID_PITCH_VISION_BUFF_ANGLE_IMAX_OUT 1.3
#define PID_PITCH_VISION_BUFF_ANGLE_MAX_OUT 2

#define PID_PITCH_VISION_BUFF_SPEED_MODE 0
#define PID_PITCH_VISION_BUFF_SPEED_KP 0.6
#define PID_PITCH_VISION_BUFF_SPEED_KI 0
#define PID_PITCH_VISION_BUFF_SPEED_KD 0
#define PID_PITCH_VISION_BUFF_SPEED_IMAX_OUT 0
#define PID_PITCH_VISION_BUFF_SPEED_MAX_OUT 4



//低通滤波参数
#define LowPass_YAW_KEY_TIME    0.28f
#define LowPass_PITCH_KEY_TIME   0.28f
#define LowPass_YAW_KEY_NUM    1.8f
#define LowPass_PITCH_KEY_NUM   1.8f

//低通滤波参数
#define LowPass_YAW_VISION_TIME    0.28f
#define LowPass_PITCH_VISION_TIME   0.28f
#define LowPass_YAW_VISION_NUM    1.5f
#define LowPass_PITCH_VISION_NUM   1.8f


//视觉yaw前馈（装甲板）（速度）
#define VISION_YAW_ALPHA 2.0f//2.0
#define VISION_YAW_BELTA 0.0f
#define VISION_YAW_OUTMAX   0.7f  //   0.7f      
//视觉pitch前馈（装甲板）
#define VISION_PITCH_ALPHA 2.0f
#define VISION_PITCH_BELTA 0.0f
#define VISION_PITCH_OUTMAX    5     //      15.0f

//视觉yaw前馈（装甲板）（加速度）
#define VISION_YAW_SPEED_ALPHA 0.02f//0.02f
#define VISION_YAW_SPEED_BELTA 0.0f
#define VISION_YAW_SPEED_OUTMAX   0.6f //0.6      


//视觉yaw前馈（符）
#define VISION_YAW_ALPHA_MECHANIASM 7.5f
#define VISION_YAW_BELTA_MECHANIASM 0.0f
#define VISION_YAW_OUTMAX_MECHANIASM           25.0f
//视觉pitch前馈（符）
#define VISION_PITCH_ALPHA_MECHANIASM 2.0f
#define VISION_PITCH_BELTA_MECHANIASM 0.0f
#define VISION_PITCH_OUTMAX_MECHANIASM 15.0f

/*-------------------------灵敏度-------------------------*/
#define SENSITIVITY_CHASSIS_RC_X  8.0
#define SENSITIVITY_CHASSIS_RC_Y  8.0
#define SENSITIVITY_CHASSIS_KEYBOARD_X  2000
#define SENSITIVITY_CHASSIS_KEYBOARD_Y  2000

#define SENSITIVITY_YAW_RC 0.0003f
#define SENSITIVITY_YAW_MOUSE 0.0005f
#define SENSITIVITY_PITCH_RC 0.00003f
#define SENSITIVITY_PITCH_MOUSE 0.0003f




/*-------------------------摩擦轮参数---------------------------*/

#define PID_FRICTIONGEAR_LEFT_MODE 0
#define PID_FRICTIONGEAR_LEFT_KP 5
#define PID_FRICTIONGEAR_LEFT_KI 0
#define PID_FRICTIONGEAR_LEFT_KD 0
#define PID_FRICTIONGEAR_LEFT_MAXIOUT 0
#define PID_FRICTIONGEAR_LEFT_MAXOUT 10000

#define PID_FRICTIONGEAR_RIGHT_MODE 0
#define PID_FRICTIONGEAR_RIGHT_KP 5
#define PID_FRICTIONGEAR_RIGHT_KI 0
#define PID_FRICTIONGEAR_RIGHT_KD 0
#define PID_FRICTIONGEAR_RIGHT_MAXIOUT 0
#define PID_FRICTIONGEAR_RIGHT_MAXOUT 10000

#define SHOOT_AVERAGE_SPEED 22
#define SHOOT_MAX_SPEED 24
#define SHOOT_MIN_SPEED 20
#define SHOOT_SPEED_ADD 20
#define SHOOT_SPEED_MINUS 30

/*-------------------------拨盘参数------------------------*/

#define SPEED_SET 200//摩擦轮转速目标值
#define Judge_AngleErr 3000//允许当前角度值与目标角度之间的偏差值3000
#define ONCE_SHOOT_ANGLE_MAILUN 35000//32768*(5/2)
#define SPEED_2006_CONTI 3600//连发转速一秒15发
//#define BACK_ANGLE_TARGET 30000          // 反转角度目标 
#define STUCK_THRESHOLD 100              // 卡弹检测阈值
#define STUCK_CURRENT_THRESHOLD   3000    // 卡弹电流阈值3000
#define STUCK_SPEED_THRESHOLD  50    // 卡弹转速阈值50    

#define PID_TIRGGER_ONCE_ANGLE_MODE 0
#define PID_TIRGGER_ONCE_ANGLE_KP 0.3 
#define PID_TIRGGER_ONCE_ANGLE_KI 0
#define PID_TIRGGER_ONCE_ANGLE_KD 0
#define PID_TIRGGER_ONCE_ANGLE_MAXIOUT 0
#define PID_TIRGGER_ONCE_ANGLE_MAXOUT 6000 

#define PID_TIRGGER_ONCE_SPEED_MODE 0
#define PID_TIRGGER_ONCE_SPEED_KP 8
#define PID_TIRGGER_ONCE_SPEED_KI 0
#define PID_TIRGGER_ONCE_SPEED_KD 0
#define PID_TIRGGER_ONCE_SPEED_MAXIOUT 0
#define PID_TIRGGER_ONCE_SPEED_MAXOUT 7000 



#define PID_TIRGGER_CONTI_SPEED_MODE 0
#define PID_TIRGGER_CONTI_SPEED_KP 15
#define PID_TIRGGER_CONTI_SPEED_KI 0
#define PID_TIRGGER_CONTI_SPEED_KD 0
#define PID_TIRGGER_CONTI_SPEED_MAXIOUT 0
#define PID_TIRGGER_CONTI_SPEED_MAXOUT 7000 //7000


//拨弹盘转速
#define   V_TIRGGER_01 240*5/2
#define   V_TIRGGER_02 480*5/2
#define   V_TIRGGER_03 720*5/2
#define   V_TIRGGER_04 960*5/2
#define   V_TIRGGER_05 1200*5/2
#define   V_TIRGGER_06 1440*5/2
#define   V_TIRGGER_07 1680*5/2
#define   V_TIRGGER_08 1920*5/2
#define   V_TIRGGER_09 2160*5/2 //每秒发9颗弹丸
#define   V_TIRGGER_10 2400 *5/2
#define   V_TIRGGER_11 2640*5/2
#define   V_TIRGGER_12 2880*5/2
#define   V_TIRGGER_13 3120*5/2
#define   V_TIRGGER_14 3360*5/2
#define   V_TIRGGER_15 3600*5/2
#define   V_TIRGGER_16 3840*5/2
#define   V_TIRGGER_17 4080*5/2
#define   V_TIRGGER_18 4320*5/2
#define   V_TIRGGER_19 4560*5/2
#define   V_TIRGGER_20 4800*5/2
#define   V_TIRGGER_21 5040*5/2
#define   V_TIRGGER_22 5280*5/2
#define   V_TIRGGER_23 5520*5/2
#define   V_TIRGGER_24 5760*5/2
#define   V_TIRGGER_25 6000*5/2
#define   V_TIRGGER_26 6240*5/2
#define   V_TIRGGER_27 6480*5/2
#define   V_TIRGGER_28 6720*5/2
#define   V_TIRGGER_29 6960*5/2

#endif
